language: rust

rust:
  - stable
    # - beta
    # - nightly
sudo: false
script:
  - cargo test
  - cargo build --release
notifications:
  email:
    on_success: never
os:
  - linux
  - osx

deploy:
  provider: releases
  file: target/release/tokio-socks5
  api_key: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: mba
