language: rust

rust:
  - stable
    # - beta
    # - nightly
sudo: false
script:
  - cargo build
  - cargo test
notifications:
  email:
    on_success: never
os:
  - linux
  - osx

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: mba
